version: "3.7"
services:
  application-authorization-service:
    image: tixfactory/application-authorization-service:latest
    container_name: application-authorization-service
    environment:
      APPLICATION_AUTHORIZATIONS_CONNECTION_STRING: "" # ME: Put the actual connection string in the quotes when deploying!
      LoggingServiceHost: logging.services.tixfactory.systems
    networks:
      tix-factory:
        aliases:
          - tix-factory-application-authorizations
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
    restart: always
networks:
  tix-factory:
    name: tix-factory