version: "3.7"
services:
  application-authorizations-service:
    image: tixfactory/application-authorizations-service:latest
    container_name: application-authorizations-service
    environment:
      APPLICATION_AUTHORIZATIONS_CONNECTION_STRING: "" # ME: Put the actual connection string in the quotes when deploying! 
    networks:
      tix-factory:
        aliases:
          - tix-factory-application-authorizations
    ports:
      - "80:80"
    restart: always
networks:
  tix-factory:
    name: tix-factory